# Get details about the registered users in the RDMS
#
SELECT ?user ?name ?givenName ?surname ?project
FROM <https://crc1625.mdi.ruhr-uni-bochum.de/graph>
WHERE {
  # Class that all persons belong to, note that we can exclude in this query as there
  # are no other entities with crc:name, etc.
  ?user a crc:User.

  # Name, given name and surname
  ?user crc:name ?name.

  # Some users don't have given names and surnames in the RDMS
  # The OPTIONAL pattern avoids excluding those users if they don't have them
  OPTIONAL {
    ?user crc:givenName ?givenName.
    ?user crc:surname ?surname.
  }

  # The project they belong to (A06, B01...)
  ?user crc:memberOfProject ?project.
}
