# You can expand the list of PREFIXes below to check how to name common classes and relations
PREFIX pmdco:   <https://w3id.org/pmd/co/> # relations and classes from our parent ontology
PREFIX pmd:   <https://w3id.org/pmd/co/> # Another shorthand for the same ontology

PREFIX : <https://crc1625.mdi.ruhr-uni-bochum.de/> # Our ontology's main prefix
PREFIX crc: <https://crc1625.mdi.ruhr-uni-bochum.de/> # You can also use this one
#
# All entities are split into different namespaces for readability, loosely
# matching their types in the ontology. They are always followed by an identifier,
# normally the object ID. Example: user:1 or measurement:48324
#
# Users and projects
PREFIX user:    <https://crc1625.mdi.ruhr-uni-bochum.de/user/>
PREFIX project:    <https://crc1625.mdi.ruhr-uni-bochum.de/project/>
#
# MLs, measurement areas and compositions
PREFIX object: <https://crc1625.mdi.ruhr-uni-bochum.de/object/>
PREFIX substrate: <https://crc1625.mdi.ruhr-uni-bochum.de/substrate/>
PREFIX measurement: <https://crc1625.mdi.ruhr-uni-bochum.de/measurement/>
PREFIX measurement_type: <https://crc1625.mdi.ruhr-uni-bochum.de/measurement_type/>
PREFIX measurement_area: <https://crc1625.mdi.ruhr-uni-bochum.de/measurement_area/>
PREFIX bulk_composition: <https://crc1625.mdi.ruhr-uni-bochum.de/bulk_composition/>
PREFIX EDX_composition: <https://crc1625.mdi.ruhr-uni-bochum.de/EDX_composition/>
#
# Workflows
PREFIX idea_or_experiment_plan: <https://crc1625.mdi.ruhr-uni-bochum.de/idea_or_experiment_plan/>
PREFIX request_for_synthesis: <https://crc1625.mdi.ruhr-uni-bochum.de/request_for_synthesis/>
PREFIX workflow_instance: <https://crc1625.mdi.ruhr-uni-bochum.de/workflow_instance/>
PREFIX workflow_model: <https://crc1625.mdi.ruhr-uni-bochum.de/workflow_model/>
PREFIX handover: <https://crc1625.mdi.ruhr-uni-bochum.de/handover/>
PREFIX activity: <https://crc1625.mdi.ruhr-uni-bochum.de/activity/>
#
# External prefixes
PREFIX rdf:     <http://www.w3.org/1999/02/22-rdf-syntax-ns#> # For expressing class relations with "rdf:type". You can also use "a".
PREFIX xsd:     <http://www.w3.org/2001/XMLSchema#> # For expressing datatypes
PREFIX foaf:    <http://xmlns.com/foaf/0.1/> # For user metadata
PREFIX prov:    <http://www.w3.org/ns/prov#> # For general metadata
PREFIX rdfs:    <http://www.w3.org/2000/01/rdf-schema#> # For "rdfs:subClassOf" relations
# For elements
PREFIX chebi: <http://purl.obolibrary.org/obo/chebi/>

SELECT ?user ?user_name ?measurement ?measurementLabel
FROM <https://crc1625.mdi.ruhr-uni-bochum.de/graph>
WHERE {
  # Look for exclusively EDX CSV measurements
  ?measurement a measurement_type:EDX_CSV.

  ?measurement rdfs:label ?measurementLabel.
  ?measurement prov:wasAttributedTo ?user.
  ?user foaf:name ?user_name.
}
