ASK WHERE {
    GRAPH <https://crc1625.mdi.ruhr-uni-bochum.de/graph/workflows> {
        ?workflow_model a crc:WorkflowModel .
        ?workflow_model crc:creator <https://crc1625.mdi.ruhr-uni-bochum.de/user/-1> .
    }
}