# Query that retrieves all measurement types, which correspond 1:1
# to the object types in the RDMS. These types are dynamically generated, and
# kept up to date with respect to the RDMS
#
# You can use these types to filter them, as can be found in `measurements_of_a_specific_file_format.sparql`
#
SELECT ?measurement_type
FROM <https://crc1625.mdi.ruhr-uni-bochum.de/graph>
WHERE {
  ?measurement_type rdfs:subClassOf pmdco:Measurement.
}