# The Knowledge Graph also represents the same types of MLs/Samples that
# the RDMS offers
#
# You can use these types to filter them, as can be seen in the rest of the queries
#
SELECT DISTINCT *
FROM <https://crc1625.mdi.ruhr-uni-bochum.de/graph>
WHERE {
  # Materials libraries
  ?ML a crc:MaterialsLibrary.

  # No gradient samples
  #?NoGradientSample a crc:NoGradientSample. # Subclass of crc:MaterialsLibrary

  # Stress chips
  #?StressChip a crc:StressChip. # Subclass of crc:MaterialsLibrary

  # Samples
  #?Sample a crc:Sample. # Subclass of crc:MaterialsLibrary

  # Stripe samples
  #?StripeSample a crc:StripeSample. # Subclass of crc:Sample

  # Computational samples
  #?ComputationalSample a crc:ComputationalSample.

  # Since the classes form a hierarchy, we can also ask for multiple of them at once
  #
  # Get all MLs and Samples, no matter their type
  #
  # a/rdfs:subClassOf* is a shorthand for "anything that is either
  # a Materials Library *or* a *subclass* of Materials Library, forming a chain (Samples...)"
  #?MLOrSample a/rdfs:subClassOf* crc:MaterialsLibrary.

  # Samples and Stripe samples
  #?Sample a/rdfs:subClassOf* crc:Sample.

  # An arbitrary combination of any of them (e.g., MLs and no gradient samples)
  #?MLOrSample a ?class.
  #FILTER (?class IN (crc:MaterialsLibrary, crc:NoGradientSample))
}