# Get MLs/Samples, misc. metadata about them and the substrate they belong to
SELECT ?MLOrSample ?externalID ?internalID ?creationDate ?user ?substrate_label
FROM <https://crc1625.mdi.ruhr-uni-bochum.de/graph>
WHERE
{
  # a/rdfs:subClassOf* is a shorthand for "anything that is either
  # a Materials Library *or* a *subclass* of Materials Library (Samples...)"
  ?MLOrSample a/rdfs:subClassOf* crc:MaterialsLibrary.

  ?MLOrSample crc:internalID ?internalID.
  ?MLOrSample crc:creationDate ?creationDate.
  ?MLOrSample crc:creator ?user.

  # The substrate is simply one of their characteristics, with a specific
  # type for them, just like in the RDMS
  ?MLOrSample crc:characteristic ?substrate.
  ?substrate a crc:Substrate.
  ?substrate crc:objectName ?substrate_label.
}
