SELECT
  (COUNT(?sample_w_handover) as ?count_w)
  (COUNT(?sample) as ?total_samples)
  (xsd:decimal(COUNT(?sample_w_handover)) / xsd:decimal(COUNT(?sample)) as ?chance_to_have_handover)
FROM <https://crc1625.mdi.ruhr-uni-bochum.de/graph>
{
    {
        SELECT DISTINCT ?sample_w_handover WHERE {
          ?sample_w_handover a crc:MaterialsLibrary.

          ?workflow_instance crc:input ?sample_w_handover.
          ?workflow_instance crc:substep ?first_handover_group.

          # The initial handover doesn't count
          ?first_handover_group crc:nextStep+/crc:substep ?handover.
        }
    }

    UNION

    {
        SELECT ?sample WHERE {
          ?sample a crc:MaterialsLibrary.
        }
    }
}
