SELECT
  (COUNT(?edx_measurement) as ?count_edx_measurement)
  (COUNT(?measurement) as ?total_measurements)
  (xsd:decimal(COUNT(?edx_measurement)) / xsd:decimal(COUNT(?measurement)) as ?chance_for_EDX_measurement)
FROM <https://crc1625.mdi.ruhr-uni-bochum.de/graph>
{
    {
        SELECT ?edx_measurement WHERE {
            ?edx_measurement a measurement_type:EDX_CSV.
        }
    }

    UNION

    {
        SELECT ?measurement WHERE {
      		?sample a :MaterialsLibrary.
      		?sample pmdco:characteristic ?measurement.
            ?measurement a ?measurement_type.
      		?measurement_type rdfs:subClassOf pmdco:Measurement.

            MINUS { ?measurement a :VolumeComposition. } # Exclude the 342 EDX compositions
        }
    }
}