SELECT (AVG(?count) AS ?max_handovers) FROM <https://crc1625.mdi.ruhr-uni-bochum.de/graph> WHERE {
  {
    {
        SELECT ?sample (COUNT(?handover) AS ?count) WHERE {
          ?sample a crc:MaterialsLibrary.

          ?workflow_instance crc:input ?sample.
          ?workflow_instance crc:substep ?first_handover_group.

          ?first_handover_group crc:nextStep*/crc:substep/crc:nextStep* ?handover.

          ?handover a crc:Handover. # Trick not to include the handover groups in the property path

        } GROUP BY ?sample
    }
  }
}