SELECT (MAX(?n_measurements) AS ?max_measurements_in_handovers) FROM <https://crc1625.mdi.ruhr-uni-bochum.de/graph> WHERE {
    SELECT ?handover (COUNT(?measurement) AS ?n_measurements) WHERE {
        ?sample_w_handover a :MaterialsLibrary.

        ?workflow_instance pmdco:input ?sample_w_handover.
        ?workflow_instance pmdco:subordinateProcess ?first_handover_group.


        ?first_handover_group pmdco:nextProcess*/pmdco:subordinateProcess* ?handover.
        ?handover pmdco:subordinateProcess ?activity.
        ?activity pmdco:output ?measurement.

        # Exclude EDX compositions, we only consider the CSV file
        FILTER NOT EXISTS {
            ?measurement a pmdco:ChemicalComposition.
        }
    } GROUP BY ?handover
}