SELECT (AVG(?n_measurements) AS ?max_measurements_in_sample_pieces) FROM <https://crc1625.mdi.ruhr-uni-bochum.de/graph> WHERE {
  SELECT ?sample_w_measurement (COUNT(?measurement) AS ?n_measurements) WHERE {
    ?sample_w_measurement a :MaterialsLibrary.

    ?sample_w_measurement pmdco:characteristic ?measurement.

    MINUS { ?measurement a :VolumeComposition. } # Exclude the 342 EDX compositions
    # It's a sample piece
    ?another_sample pmdco:composedOf ?sample_w_measurement.
  } GROUP BY ?sample_w_measurement
}