DELETE {
    GRAPH <https://crc1625.mdi.ruhr-uni-bochum.de/graph/workflows> {
        <{workflow_instance_iri}> crc:lastValidatedAt ?last_validated_at.
        <{workflow_instance_iri}> crc:cachedValidationStatus ?cached_validation_status.
        <{workflow_instance_iri}> crc:validationCacheStale ?validation_cache_stale.
        <{workflow_instance_iri}> crc:validationCacheHash ?validation_cache_hash.
    }
}
INSERT {
    GRAPH <https://crc1625.mdi.ruhr-uni-bochum.de/graph/workflows> {
        <{workflow_instance_iri}> crc:lastValidatedAt "{last_validated_at}"^^xsd:dateTime.
        <{workflow_instance_iri}> crc:cachedValidationStatus "{cached_validation_status}"^^xsd:string.
        <{workflow_instance_iri}> crc:validationCacheStale {validation_cache_stale}.
        <{workflow_instance_iri}> crc:validationCacheHash "{validation_cache_hash}"^^xsd:string.
    }
}
WHERE {
    GRAPH <https://crc1625.mdi.ruhr-uni-bochum.de/graph/workflows> {
        OPTIONAL { <{workflow_instance_iri}> crc:lastValidatedAt ?last_validated_at. }
        OPTIONAL { <{workflow_instance_iri}> crc:cachedValidationStatus ?cached_validation_status. }
        OPTIONAL { <{workflow_instance_iri}> crc:validationCacheStale ?validation_cache_stale. }
        OPTIONAL { <{workflow_instance_iri}> crc:validationCacheHash ?validation_cache_hash. }
    }
}
