# Get details about the registered users in the RDMS
#
SELECT ?user ?name ?givenName ?surname ?project
FROM <https://crc1625.mdi.ruhr-uni-bochum.de/graph>
WHERE {
  # Class that all persons belong to, note that we can exclude in this query as there
  # are no other entities with foaf:name, etc.
  ?user a pmdco:Operator.

  # Name, given name and surname
  ?user foaf:name ?name.

  # Some users don't have given names and surnames in the RDMS
  # The OPTIONAL pattern avoids excluding those users if they don't have them
  OPTIONAL {
    ?user foaf:givenName ?givenName.
    ?user foaf:surname ?surname.
  }

  # The project they belong to (A06, B01...)
  ?user :memberOfProject ?project.
}
