SELECT ?user ?user_name ?measurement ?measurement_label
FROM <https://crc1625.mdi.ruhr-uni-bochum.de/graph>
WHERE {
  # crc:UploadedFile is the high-level type for any kind of upload in the
  # RMDS (i.e., an object in the RDMS that is linked to a ML/Sample that is not
  # another ML/sample, special object such as a handover, etc.).
  ?measurement a crc:UploadedFile.

  # Get their textual label and comment
  ?measurement crc:objectName ?measurement_label.

  # Get its author
  ?measurement crc:creator ?user.
  # and their name
  ?user crc:name ?user_name.
}
