DELETE {
    GRAPH <https://crc1625.mdi.ruhr-uni-bochum.de/graph/workflows> {
        ?handover_workflow_instance crc:hasAssignment ?assignment.
        ?assignment ?p_assignment ?o_assignment.
    }
}
WHERE {
  GRAPH <https://crc1625.mdi.ruhr-uni-bochum.de/graph/workflows> {
    {
      <{handover_workflow_instance_iri}> crc:hasAssignment ?assignment.
      ?assignment crc:relatesToHandoverWorkflowStep ?workflow_model_step.

      # The workflow model step is orphaned (everything but this link was deleted)
      FILTER NOT EXISTS {
        ?workflow_model_step ?p ?o.
      }

      ?assignment ?p_assignment ?o_assignment.

      BIND(<{handover_workflow_instance_iri}> AS ?handover_workflow_instance).
    }
  }
}
