SELECT DISTINCT ?handover_group_1 ?handover_group_2 WHERE {
	GRAPH <https://crc1625.mdi.ruhr-uni-bochum.de/graph> {
		?workflow_instance a :HandoverWorkflowInstance.
		?MLOrSample a/rdfs:subClassOf* pmdco:EngineeredMaterial.

		?workflow_instance pmdco:input ?MLOrSample.
		?MLOrSample :internalID {object_id}.

		?workflow_instance pmdco:subordinateProcess ?first_handover_group.

		?first_handover_group pmdco:nextProcess* ?handover_group_1.

		?handover_group_1 pmdco:nextProcess ?handover_group_2.
	}
}