DELETE {
    GRAPH <https://crc1625.mdi.ruhr-uni-bochum.de/graph/workflows> {
        ?workflow_instance crc:handoverWorkflowModelInstanceOf <{old_workflow_model_iri}>.
    }
}
INSERT {
    GRAPH <https://crc1625.mdi.ruhr-uni-bochum.de/graph/workflows> {
        ?workflow_instance crc:handoverWorkflowModelInstanceOf <{new_workflow_model_iri}>.
    }
}
WHERE {
  GRAPH <https://crc1625.mdi.ruhr-uni-bochum.de/graph/workflows> {
        ?workflow_instance crc:handoverWorkflowModelInstanceOf <{old_workflow_model_iri}>.
  }
}
